@echo off
setlocal enabledelayedexpansion

echo.
echo ================================================================
echo  DAWATI AUTONOMOUS TESTER - AUTO SETUP
echo  Powered by Playwright + Gemini AI
echo ================================================================
echo.
echo This script will:
echo   [1] Check/Install Node.js
echo   [2] Install all dependencies
echo   [3] Install Playwright browsers
echo   [4] Configure your settings
echo   [5] Build the project
echo.
echo ================================================================
echo.
pause

REM Check if Node.js is installed
echo.
echo [1/5] Checking Node.js installation...
node --version >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo Node.js is not installed!
    echo.
    echo Please install Node.js first:
    echo   1. Go to https://nodejs.org
    echo   2. Download the LTS version
    echo   3. Run the installer
    echo   4. Run this script again
    echo.
    echo Or install via winget:
    echo   winget install OpenJS.NodeJS.LTS
    echo.
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
echo   [OK] Node.js %NODE_VERSION% found

REM Check npm
npm --version >nul 2>&1
if %errorlevel% neq 0 (
    echo   [ERROR] npm not found
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('npm --version') do set NPM_VERSION=%%i
echo   [OK] npm %NPM_VERSION% found

REM Install dependencies
echo.
echo [2/5] Installing dependencies...
echo   This may take 2-3 minutes...
call npm install --silent
if %errorlevel% neq 0 (
    echo   [ERROR] Failed to install dependencies
    pause
    exit /b 1
)
echo   [OK] Dependencies installed

REM Install Playwright browsers
echo.
echo [3/5] Installing Playwright browsers...
echo   Downloading Chromium (this may take a while)...
call npx playwright install chromium
if %errorlevel% neq 0 (
    echo   [WARNING] Playwright browser installation had issues
    echo   You may need to run: npx playwright install
)
echo   [OK] Playwright browsers installed

REM Configuration
echo.
echo [4/5] Configuration
echo.
echo ================================================================
echo  Please provide your configuration:
echo ================================================================
echo.

REM Check if .env already exists
if exist .env (
    echo   .env file already exists.
    set /p OVERWRITE="   Overwrite? (y/n): "
    if /i not "!OVERWRITE!"=="y" (
        echo   Keeping existing configuration.
        goto BUILD
    )
)

REM Get Gemini API Key
echo.
echo   Get your Gemini API key from:
echo   https://aistudio.google.com/apikey
echo.
set /p GEMINI_KEY="   Enter your Gemini API key: "
if "!GEMINI_KEY!"=="" (
    echo   [ERROR] Gemini API key is required
    pause
    exit /b 1
)

REM Get Dawati URL
echo.
set /p DAWATI_URL="   Enter your Dawati app URL: "
if "!DAWATI_URL!"=="" (
    echo   [ERROR] Dawati URL is required
    pause
    exit /b 1
)

REM Optional: Test phone
echo.
set /p TEST_PHONE="   Test phone number (optional, press Enter to skip): "

REM Optional: Test email
set /p TEST_EMAIL="   Test email (optional, press Enter to skip): "

REM Create .env file
echo.
echo   Creating .env file...
(
echo # Dawati Autonomous Tester Configuration
echo # Generated by auto-setup.bat
echo.
echo GEMINI_API_KEY=!GEMINI_KEY!
echo DAWATI_URL=!DAWATI_URL!
echo.
echo # Test credentials
if not "!TEST_PHONE!"=="" echo TEST_PHONE=!TEST_PHONE!
if not "!TEST_EMAIL!"=="" echo TEST_EMAIL=!TEST_EMAIL!
echo.
echo # Browser settings
echo HEADLESS=true
echo SLOW_MO=0
echo VIEWPORT_WIDTH=1280
echo VIEWPORT_HEIGHT=720
echo.
echo # Screenshot settings
echo FULL_PAGE_SCREENSHOTS=true
echo SCREENSHOT_QUALITY=80
echo.
echo # AI settings
echo AI_MODEL=gemini-2.0-flash-exp
echo AI_MAX_TOKENS=4096
echo AI_TEMPERATURE=0.3
echo.
echo # Logging
echo LOG_LEVEL=info
) > .env

echo   [OK] Configuration saved to .env

:BUILD
REM Build the project
echo.
echo [5/5] Building project...
call npm run build
if %errorlevel% neq 0 (
    echo   [ERROR] Build failed
    pause
    exit /b 1
)
echo   [OK] Project built successfully

echo.
echo ================================================================
echo  SETUP COMPLETE!
echo ================================================================
echo.
echo  Your autonomous testing system is ready!
echo.
echo  Commands:
echo    npm run test         Run full test with AI analysis
echo    npm run test:auth    Run only auth tests
echo    npm run test:nav     Run only navigation tests
echo    npm run report       Open latest report
echo.
echo  Results will be saved to: test-results\
echo.
echo ================================================================
echo.
set /p RUN_NOW="  Run a test now? (y/n): "
if /i "!RUN_NOW!"=="y" (
    echo.
    echo  Starting test...
    call npm run test
)

echo.
echo  Done! Press any key to exit.
pause >nul
